
SECRET_KEY = 'dev'
DEBUG = False

SQLALCHEMY_DATABASE_URI = 'sqllite:///database.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False

ACCESS_TOKEN_MINUTES = 30
REFRESH_TOKEN_DAYS = 3
REFRESH_TOKEN_IN_BODY = True
RESET_TOKEN_MINUTES = 10


APIFAIRY_TITLE = 'CostWise Fitec API'
APIFAIRY_VERSION = '1.0'
APIFAIRY_UI = 'swagger_ui'
APIFAIRY_TAGS = ['tokens', 'users', 'projects']

MAIL_SERVER = 'smtp.gmail.com'
MAIL_USE_TLS = True
MAIL_PORT = 587
