
SECRET_KEY = 'dev'
DEBUG = False

SQLALCHEMY_TRACK_MODIFICATIONS = False

ACCESS_TOKEN_MINUTES = 30
REFRESH_TOKEN_DAYS = 3
REFRESH_TOKEN_IN_BODY = True

APIFAIRY_TITLE = 'CostWise Fitec API'
APIFAIRY_VERSION = '1.0'
APIFAIRY_UI = 'swagger_ui'
APIFAIRY_TAGS = ['tokens', 'users']
